name: "deploy"
on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: ["tag"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Lint
        run: deno lint
      - name: Test
        run: deno test
      - name: Build
        run: deno compile -o dist/ci-test index.ts
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            dist
