name: "deploy"
on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: [tag]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to release
        required: true

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        id: get_tag
        run: |
          input_tag=${{ github.event.inputs.tag }}
          event_tag=${{ github.event.ref }}
          
          # If input tag not defined use event tag
          deploy_tag="${input_tag:-$event_tag}"
          
          # If event tag not defined use latest tag
          deploy_tag="${deploy_tag:-$latest_tag}"
          
          echo "Input tag: $input_tag"
          echo "Event tag: $event_tag"
          echo "Latest tag: $latest_tag"
          echo "Deploy tag: $deploy_tag"

          git checkout --quiet $deploy_tag

          echo "::set-output name=deploy_tag::$deploy_tag"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Lint
        run: deno lint
      - name: Test
        run: deno test
      - name: Build
        run: deno compile -o dist/ci-test index.ts
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: dist
          tag_name: ${{ steps.get_tag.outputs.deploy_tag }}
          generate_release_notes: true
