name: "deploy"
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: Semver level to create a tag for
        required: false
        default: patch
        options:
          - major
          - minor
          - patch
      tag:
        description: Existing tag to release
        required: false

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Create tag
        id: create_tag
        if: ${{ !startsWith(github.event.inputs.tag, 'v') && !startsWith(github.ref, 'refs/tags/') }}
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.level }}
      - name: Get tag
        id: get_tag
        run: |
          git fetch tags --quiet

          input_tag=${{ github.event.inputs.tag }}
          created_tag=${{ steps.create_tag.outputs.new_tag }}
          event_tag=${{ github.event.ref }}

          # Use input tag or created tag
          deploy_tag="${input_tag:-$created_tag}"

          # If created tag not defined use event tag
          deploy_tag="${deploy_tag:-$event_tag}"

          echo "Input tag: $input_tag"
          echo "Created tag: $created_tag"
          echo "Event tag: $event_tag"
          echo "Deploy tag: $deploy_tag"

          git checkout --quiet $deploy_tag

          echo "::set-output name=deploy_tag::${deploy_tag}"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Lint
        run: deno lint
      - name: Test
        run: deno test
      - name: Build
        run: deno compile -o dist/ci-test index.ts
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: dist/**
          tag_name: ${{ steps.get_tag.outputs.deploy_tag }}
          generate_release_notes: true
