name: tag
on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: Level
        required: true
        default: patch
        options:
          - major
          - minor
          - patch
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.level }}
